---
title: "R Notebook"
output: html_notebook
---
- each player has a different assignment on a given play, likley unable to know with public data
- a run play vs a pass play will likely need to be evaluated differentl
-
```{r}
library(tidyverse)
library(gganimate)
library(ggforce)
library(googlesheets4)
```

```{r}
games_df<-read_csv('games.csv')

players_df <- read_csv("players.csv")

plays_df <- read_csv("plays.csv")

tackles_df<- read_csv("tackles.csv")

track_df <- read_csv("tracking_week_2.csv")

```



```{r}
# trackles_df <- track_df %>% 
#   filter(gameId == 2022090800 & event == "pass_outcome_caught" & playId == 56)%>% #for qual control
#   left_join(tackles_df, by = c("gameId","playId","nflId")) %>%
#   left_join(select(plays_df,c(gameId,playId,ballCarrierId)), by = c("gameId","playId")) %>%
#   mutate(tackle = if_else(is.na(tackle),0,tackle)) %>%
#   group_by(gameId,playId,frameId)%>%
#   mutate(bc_x = max(if_else(nflId == ballCarrierId,x,NA),na.rm=T),
#          bc_y = max(if_else(nflId == ballCarrierId,y,NA),na.rm=T),
#          dist_from_bc = sqrt(((x-bc_x)^2)+((y-bc_y)^2)),
#          ball_x = max(if_else(is.na(nflId),x,NA),na.rm=T),
#          ball_y = max(if_else(is.na(nflId),y,NA),na.rm=T),
#          dist_from_ball = sqrt(((x-ball_x)^2)+((y-ball_y)^2))
#          
#   )
  
```
field control
```{r}
play_ <- plays_df %>% 
  dplyr::filter(gameId == 2022091800 & playId == 2801) %>%
  dplyr::select(gameId, playId, possessionTeam, playDescription, absoluteYardlineNumber, yardsToGo) 

game_ <- games_df %>%
  dplyr::filter(gameId == play_$gameId)

 track_play<- track_df %>% 
   filter(gameId == 2022091800 & playId == 2801)%>%
    select(x, y, s, dir, event, displayName, jerseyNumber, frameId, club,playDirection)%>%
   mutate(
        dir_rad = dir * pi / 180,
        v_x = sin(dir_rad) * s,
        v_y = cos(dir_rad) * s,
        v_theta = atan(v_y / v_x),
        v_theta = ifelse(is.nan(v_theta), 0, v_theta),
        #is_home = if_else(club == game_$homeTeamAbbr[1],T,F)
   )%>%
   select(frameId, event,club, jerseyNumber, displayName, x, y, s, v_theta, v_x, v_y,playDirection,)
 
 play_direction_ <- track_play %>% head(1) %>% dplyr::pull(playDirection)

```


```{r}
plot_field <- function(field_color = "#ffffff", line_color = "#212529", number_color = "#adb5bd") {
    field_height <- 160/3
    field_width <- 120
    
    field <- ggplot() +
        theme_minimal() +
        theme(
            plot.title = element_text(size = 13, hjust = .5),
            plot.subtitle = element_text(hjust = 1),
            legend.position = "bottom",
            legend.title.align = 1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_blank(),
            axis.ticks = element_blank(),
            axis.text = element_blank(),
            axis.line = element_blank(),
            panel.background = element_rect(fill = field_color, color = "white"),
            panel.border = element_blank(),
            aspect.ratio = field_height/field_width
    ) +
        # major lines
    annotate(
      "segment",
      x = c(0, 0, 0,field_width, seq(10, 110, by=5)),
      xend = c(field_width,field_width, 0, field_width, seq(10, 110, by=5)),
      y = c(0, field_height, 0, 0, rep(0, 21)),
      yend = c(0, field_height, field_height, field_height, rep(field_height, 21)),
      colour = line_color
    ) +
    # hashmarks
    annotate(
      "segment",
      x = rep(seq(10, 110, by=1), 4),
      xend = rep(seq(10, 110, by=1), 4),
      y = c(rep(0, 101), rep(field_height-1, 101), rep(160/6 + 18.5/6, 101), rep(160/6 - 18.5/6, 101)),
      yend = c(rep(1, 101), rep(field_height, 101), rep(160/6 + 18.5/6 + 1, 101), rep(160/6 - 18.5/6 - 1, 101)),
      colour = line_color
    ) +
    # yard numbers
    annotate(
      "text",
      x = seq(20, 100, by = 10),
      y = rep(12, 9),
      label = c(seq(10, 50, by = 10), rev(seq(10, 40, by = 10))),
      size = 10,
      colour = number_color,
    ) +
    # yard numbers upside down
    annotate(
      "text",
      x = seq(20, 100, by = 10),
      y = rep(field_height-12, 9),
      label = c(seq(10, 50, by = 10), rev(seq(10, 40, by = 10))),
      angle = 180,
      size = 10,
      colour = number_color, 
    )
  
  return(field)
}
 
fetch_team_colors <- function(team_colors_=NULL, h_team_, a_team_, diverge_=FALSE) {
    colors_url <- "https://raw.githubusercontent.com/asonty/ngs_highlights/master/utils/data/nfl_team_colors.tsv"
    #^^ngs highlights tracking data??
    
    if (is.null(team_colors_)) {
        team_colors_ <- suppressMessages(readr::read_tsv(colors_url))
    }
  
    h_team_color1 <- team_colors_ %>% filter(teams == h_team_) %>% pull(color1)
    h_team_color2 <- team_colors_ %>% filter(teams == h_team_) %>% pull(color2)
    a_team_color1 <- team_colors_ %>% filter(teams == a_team_) %>% pull(color1)
    a_team_color2 <- team_colors_ %>% filter(teams == a_team_) %>% pull(color2)
  
    if (diverge_ == TRUE) {
        h_team_color1_family <- team_colors_ %>% filter(teams == h_team_) %>% select(color1_family) %>% pull()
        a_team_color1_family <- team_colors_ %>% filter(teams == a_team_) %>% select(color1_family) %>% pull()
    
        if (h_team_color1_family == a_team_color1_family) {
            a_team_color1 <- team_colors_ %>% filter(teams == a_team_) %>% select(color2) %>% pull()
          a_team_color2 <- team_colors_ %>% filter(teams == a_team_) %>% select(color1) %>% pull()
        }
    }
    
    df_colors <- tibble(
        home_1 = h_team_color1, home_2 = h_team_color2, away_1 = a_team_color1, away_2 = a_team_color2
    )
    
  
    return(df_colors)
}  
##now animating for our play
 ## direction up or down field       
if (play_direction_ == "left") {
    line_of_scrimmage = play_$absoluteYardlineNumber
    to_go_line = line_of_scrimmage - play_$yardsToGo
} else {
    line_of_scrimmage = play_$absoluteYardlineNumber
    to_go_line = line_of_scrimmage + play_$yardsToGo
}

df_colors <- fetch_team_colors(h_team_ = game_$homeTeamAbbr, a_team_ = game_$visitorTeamAbbr, diverge_ = T)

play_frames <- plot_field() + 
  geom_voronoi_segment(data=track_play %>% dplyr::filter(club != 'football')
                       , aes(x,y))+
    # line of scrimmage
    annotate(
        "segment",
        x = line_of_scrimmage, xend = line_of_scrimmage, y = 0, yend = 160/3,
        colour = "#0d41e1", size = 1.5
    ) +
    # 1st down marker
    annotate(
        "segment",
        x = to_go_line, xend = to_go_line, y = 0, yend = 160/3,
        colour = "#f9c80e", size = 1.5
    ) +
    # away team velocities
    geom_segment(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = df_colors$away_1, size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) + 
    # home team velocities
    geom_segment(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = df_colors$home_2, size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) +
    # away team locs and jersey numbers
    geom_point(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y),
        fill = "#f8f9fa", colour = df_colors$away_2,
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
    geom_text(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = df_colors$away_1, size = 4.5
    ) +
    # home team locs and jersey numbers
    geom_point(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y),
        fill = df_colors$home_1, colour = df_colors$home_2,
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
    geom_text(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = df_colors$home_2, size = 4.5, 
    ) +
    # ball
    geom_point(
        data = track_play %>% dplyr::filter(club == "football"),
        mapping = aes(x = x, y = y),
        fill = "#935e38", colour = "#d9d9d9",
        shape = 21, alpha = 1, size = 4, stroke = 1
    ) +
    # title 
    labs(title = play_$playDescription) +
    # animation stuff
    transition_time(frameId)  +
    ease_aes('linear')+
    NULL

play_length <- length(unique(track_play$frameId))
play_anim <- animate(
  play_frames,
  fps = 10, 
  nframe = play_length,
  width = 800,
  height = 400,
  end_pause = 0
)

play_anim
```

```{r}

```

