---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(googledrive)
library(gt)
library(gganimate)
library(ggforce)
googledrive::drive_download('team_rankings.csv')
  googledrive::drive_download('linebackers_rankings.csv')
  googledrive::drive_download('defensive_front_rankings.csv')
  googledrive::drive_download('defensive_backs_rankings.csv')
  googledrive::drive_download('cleveland_browns.csv')
  googledrive::drive_download('algo_output_NO_WEATHER_data_week_1.csv')
  
  team_rankings <- read_csv('team_rankings.csv')
  linebackers_rank <- read_csv('linebackers_rankings.csv')
  defensive_front_rank <- read_csv('defensive_front_rankings.csv')
  db_rank<-read_csv('defensive_backs_rankings.csv')
  browns<-read_csv('cleveland_browns.csv')
  NO_WEATHER <- read.csv('algo_output_NO_WEATHER_data_week_1.csv')
```

```{r}


play_ <- plays_df %>% 
  dplyr::filter(gameId == 2022091102 & playId == 1907) %>%
  dplyr::select(gameId, playId, possessionTeam, playDescription, absoluteYardlineNumber, yardsToGo) 

game <- games_df %>%
  dplyr::filter(gameId == play_$gameId)

raw_track_wk1 <- read_csv('tracking_week_1.csv')
  
 track_play_NO_WEATHER<- raw_track_wk1 %>% 
   left_join(NO_WEATHER%>%select(c(ends_with('Id'),starts_with('p'))))%>%
   filter(gameId == 2022091102 & playId == 1907)%>%
    select(x, y, s, dir, displayName, jerseyNumber, frameId, club,playDirection,starts_with('p'))%>%
   mutate(
        dir_rad = dir * pi / 180,
        v_x = sin(dir_rad) * s,
        v_y = cos(dir_rad) * s,
        v_theta = atan(v_y / v_x),
        v_theta = ifelse(is.nan(v_theta), 0, v_theta),
        is_home = if_else(club == game_$homeTeamAbbr[1],T,F)
   )%>%
   select(frameId,club, jerseyNumber, displayName, x, y, s, v_theta, v_x, v_y,playDirection,starts_with('p'))%>%
   group_by(frameId)%>%
   mutate(maxTackle = if_else(p.Tackle. == max(p.Tackle., na.rm = T),T,F))
 
 play_direction_ <- track_play_NO_WEATHER %>% head(1) %>% dplyr::pull(playDirection)

```

```{r}
plot_field <- function(field_color = "#ffffff", line_color = "#212529", number_color = "#adb5bd") {
    field_height <- 160/3
    field_width <- 120
    
    field <- ggplot() +
        theme_minimal() +
        theme(
            plot.title = element_text(size = 13, hjust = .5),
            plot.subtitle = element_text(hjust = 1),
            legend.position = "bottom",
            legend.title.align = 1,
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_blank(),
            axis.ticks = element_blank(),
            axis.text = element_blank(),
            axis.line = element_blank(),
            panel.background = element_rect(fill = field_color, color = "white"),
            panel.border = element_blank(),
            aspect.ratio = field_height/field_width
    ) +
        # major lines
    annotate(
      "segment",
      x = c(0, 0, 0,field_width, seq(10, 110, by=5)),
      xend = c(field_width,field_width, 0, field_width, seq(10, 110, by=5)),
      y = c(0, field_height, 0, 0, rep(0, 21)),
      yend = c(0, field_height, field_height, field_height, rep(field_height, 21)),
      colour = line_color
    ) +
    # hashmarks
    annotate(
      "segment",
      x = rep(seq(10, 110, by=1), 4),
      xend = rep(seq(10, 110, by=1), 4),
      y = c(rep(0, 101), rep(field_height-1, 101), rep(160/6 + 18.5/6, 101), rep(160/6 - 18.5/6, 101)),
      yend = c(rep(1, 101), rep(field_height, 101), rep(160/6 + 18.5/6 + 1, 101), rep(160/6 - 18.5/6 - 1, 101)),
      colour = line_color
    ) +
    # yard numbers
    annotate(
      "text",
      x = seq(20, 100, by = 10),
      y = rep(12, 9),
      label = c(seq(10, 50, by = 10), rev(seq(10, 40, by = 10))),
      size = 10,
      colour = number_color,
    ) +
    # yard numbers upside down
    annotate(
      "text",
      x = seq(20, 100, by = 10),
      y = rep(field_height-12, 9),
      label = c(seq(10, 50, by = 10), rev(seq(10, 40, by = 10))),
      angle = 180,
      size = 10,
      colour = number_color, 
    )
  
  return(field)
}
 
fetch_team_colors <- function(team_colors_=NULL, h_team_, a_team_, diverge_=FALSE) {
    colors_url <- "https://raw.githubusercontent.com/asonty/ngs_highlights/master/utils/data/nfl_team_colors.tsv"
    #^^ngs highlights tracking data??
    
    if (is.null(team_colors_)) {
        team_colors_ <- suppressMessages(readr::read_tsv(colors_url))
    }
  
    h_team_color1 <- team_colors_ %>% filter(teams == h_team_) %>% pull(color1)
    h_team_color2 <- team_colors_ %>% filter(teams == h_team_) %>% pull(color2)
    a_team_color1 <- team_colors_ %>% filter(teams == a_team_) %>% pull(color1)
    a_team_color2 <- team_colors_ %>% filter(teams == a_team_) %>% pull(color2)
  
    if (diverge_ == TRUE) {
        h_team_color1_family <- team_colors_ %>% filter(teams == h_team_) %>% select(color1_family) %>% pull()
        a_team_color1_family <- team_colors_ %>% filter(teams == a_team_) %>% select(color1_family) %>% pull()
    
        if (h_team_color1_family == a_team_color1_family) {
            a_team_color1 <- team_colors_ %>% filter(teams == a_team_) %>% select(color2) %>% pull()
          a_team_color2 <- team_colors_ %>% filter(teams == a_team_) %>% select(color1) %>% pull()
        }
    }
    
    df_colors <- tibble(
        home_1 = h_team_color1, home_2 = h_team_color2, away_1 = a_team_color1, away_2 = a_team_color2
    )
    
  
    return(df_colors)
}  
##now animating for our play
 ## direction up or down field       
if (play_direction_ == "left") {
    line_of_scrimmage = play_$absoluteYardlineNumber
    to_go_line = line_of_scrimmage - play_$yardsToGo
} else {
    line_of_scrimmage = play_$absoluteYardlineNumber
    to_go_line = line_of_scrimmage + play_$yardsToGo
}

df_colors <- fetch_team_colors(h_team_ = game_$homeTeamAbbr, a_team_ = game_$visitorTeamAbbr, diverge_ = T)

play_frames_NO_WEATHER <- plot_field() + 
    # line of scrimmage
    annotate(
        "segment",
        x = line_of_scrimmage, xend = line_of_scrimmage, y = 0, yend = 160/3,
        colour = "#0d41e1", size = 1.5
    ) +
    # 1st down marker
    annotate(
        "segment",
        x = to_go_line, xend = to_go_line, y = 0, yend = 160/3,
        colour = "#f9c80e", size = 1.5
    ) +
    # away team velocities
    geom_segment(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = df_colors$away_1, size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) + 
    # home team velocities
    geom_segment(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = '#0B162A', size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) +
    # away team locs and jersey numbers
    geom_point(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, fill = maxTackle),
        colour = '#AA0000',
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
   scale_fill_manual(values = c('white',
                                 'gold'))+
    geom_text(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = df_colors$away_1, size = 4.5
    ) +
    # home team locs and jersey numbers
    geom_point(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y),
        fill = 'white', colour = '#0B162A',
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
    geom_text(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = '#0B162A', size = 4.5, 
    ) +
    # ball
    geom_point(
        data = track_play_NO_WEATHER %>% dplyr::filter(club == "football"),
        mapping = aes(x = x, y = y),
        fill = "#935e38", colour = "#d9d9d9",
        shape = 21, alpha = 1, size = 4, stroke = 1
    ) +
    # title 
    labs(title = play_$playDescription) +
   theme(legend.position = 'None')+
    # animation stuff
    transition_time(frameId)  +
    ease_aes('linear')+
    NULL

play_length <- length(unique(track_play_NO_WEATHER$frameId))
play_anim_NO_WEATHER <- animate(
  play_frames_NO_WEATHER,
  fps = 10, 
  nframe = play_length,
  width = 800,
  height = 400,
  end_pause = 0
)

play_anim_NO_WEATHER
```


```{r}
track_play<- raw_track_wk1 %>% 
   left_join(algo_output_data_week_1%>%select(c(ends_with('Id'),starts_with('p'))))%>%
   filter(gameId == 2022091102 & playId == 1907)%>%
    select(x, y, s, dir, displayName, jerseyNumber, frameId, club,playDirection,starts_with('p'))%>%
   mutate(
        dir_rad = dir * pi / 180,
        v_x = sin(dir_rad) * s,
        v_y = cos(dir_rad) * s,
        v_theta = atan(v_y / v_x),
        v_theta = ifelse(is.nan(v_theta), 0, v_theta),
        is_home = if_else(club == game_$homeTeamAbbr[1],T,F)
   )%>%
   select(frameId,club, jerseyNumber, displayName, x, y, s, v_theta, v_x, v_y,playDirection,starts_with('p'))%>%
   group_by(frameId)%>%
   mutate(maxTackle = if_else(p.Tackle. == max(p.Tackle., na.rm = T),T,F))


play_frames <- plot_field() + 
    # line of scrimmage
    annotate(
        "segment",
        x = line_of_scrimmage, xend = line_of_scrimmage, y = 0, yend = 160/3,
        colour = "#0d41e1", size = 1.5
    ) +
    # 1st down marker
    annotate(
        "segment",
        x = to_go_line, xend = to_go_line, y = 0, yend = 160/3,
        colour = "#f9c80e", size = 1.5
    ) +
    # away team velocities
    geom_segment(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = df_colors$away_1, size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) + 
    # home team velocities
    geom_segment(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, xend = x + v_x, yend = y + v_y),
        colour = '#0B162A', size = 1, arrow = arrow(length = unit(0.01, "npc"))
    ) +
    # away team locs and jersey numbers
    geom_point(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, fill = maxTackle),
        colour = '#AA0000',
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
    scale_fill_manual(values = c('white',
                                 'gold'))+
    geom_text(
        data = track_play %>% dplyr::filter(club == game_$visitorTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = df_colors$away_1, size = 4.5
    ) +
    # home team locs and jersey numbers
    geom_point(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y),
        fill = 'white', colour = '#0B162A',
        shape = 21, alpha = 1, size = 8, stroke = 1.5
    ) +
    geom_text(
        data = track_play %>% dplyr::filter(club == game_$homeTeamAbbr),
        mapping = aes(x = x, y = y, label = jerseyNumber),
        colour = '#0B162A', size = 4.5, 
    ) +
    # ball
    geom_point(
        data = track_play %>% dplyr::filter(club == "football"),
        mapping = aes(x = x, y = y),
        fill = "#935e38", colour = "#d9d9d9",
        shape = 21, alpha = 1, size = 4, stroke = 1
    ) +
    # title 
    labs(title = play_$playDescription) +
    theme(legend.position = 'None')+
    geom_text(data = track_play, aes(label = frameId, x = 60, y = -10))+
    # animation stuff
    transition_time(frameId)  +
    ease_aes('linear')+
    NULL

play_length <- length(unique(track_play$frameId))
play_anim <- animate(
  play_frames,
  fps = 10, 
  nframe = play_length,
  width = 800,
  height = 400,
  end_pause = 0
)

play_anim
```


```{r}
anim_save('no_weather.gif',play_anim_NO_WEATHER)
anim_save('bears_niners.gif',play_anim)
```

```{r}
track_play_linegraph <- track_play %>%
  group_by(displayName)%>%
  arrange((frameId))%>%
  mutate(
        cross_LOS_frame = case_when(
                    (displayName == 'Justin Fields' & lag(x) < 65 & x >= 65 ) & ((65 - lag(x)) >= (x - 65)) ~ frameId,
                    (displayName == 'Justin Fields' & lag(x) < 65 & x >= 65 ) & ((65 - lag(x)) < (x - 65)) ~ lag(frameId),
                    T ~ 0
                            ),
        first_dwn_frame = case_when(
                    (displayName == 'Justin Fields' & lag(x) < 73 & x >= 73 ) & ((73 - lag(x)) >= (x - 73)) ~ frameId,
                    (displayName == 'Justin Fields' & lag(x) < 73 & x >= 73 ) & ((73 - lag(x)) < (x - 73)) ~ lag(frameId),
                    T ~ 0
                            ),
        ) %>%
  ungroup()%>%
  mutate(cross_LOS_frame = max(cross_LOS_frame),
         first_dwn_frame = max(first_dwn_frame))




  ggplot() +
    geom_line(
    data = track_play,
    aes(x = frameId,y = p.Tackle., group = displayName),
    color = 'grey'
    )+
  geom_line(
    data = track_play %>% filter(displayName == 'Samson Ebukam'),
    aes(x = frameId,y = p.Tackle.),
    size = 1.5,
    color = 'black'
    ) +
  geom_line(
    data = track_play %>% filter(displayName == 'Fred Warner'),
    aes(x = frameId,y = p.Tackle.),
    color = '#aa0000',
    size = 1.5
    ) +
  geom_line(
    data = track_play %>% filter(displayName == 'Samuel Womack'),
    aes(x = frameId,y = p.Tackle.),
    color = '#b3995d',
    size = 1.5
    ) +
  geom_vline(xintercept=5, linetype = 2) +
  geom_vline(xintercept = max(track_play_linegraph$cross_LOS_frame), linetype = 2, colour = "#0d41e1") +
  geom_vline(xintercept = max(track_play_linegraph$first_dwn_frame), linetype = 2, colour = "#f9c80e") +
  geom_vline(xintercept = max(track_play_linegraph$frameId) - 5, linetype = 2) +
  geom_text(label = 'Ebukam', aes(x=7.5,y=.87),fontface='bold') +
  geom_text(label = 'Warner', aes(x=20,y=.5), color = '#aa0000',fontface='bold')+
  geom_text(label = 'Womack', aes(x = 46, y = .61), fontface='bold', color = '#b3995d')+
  scale_x_continuous(breaks = c(5,27,37,42),
                   labels = (c('Ebukam Missed Tackle',
                            'Cross LOS', 
                            '1st Down',
                            'End Of Play'))
                   ) + 
  xlab('Events on Play') +
  ylab('Tackle Probability')+
  labs(title = '49ers Defenders Tackle Liklihood Over the Course of the Play') +
  theme_classic()

```

```{r}
#tmDefRk

top_16 <-
team_rankings%>%
  head(16)%>%
  inner_join(nflfastR::teams_colors_logos, by = c('club' = 'team_abbr'))%>%
  select(club,team_logo_espn,team_wordmark,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header("Top Half Team AdjTVOE ") %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_hide(c(club,team_logo_espn)) %>%
  cols_label(
    team_wordmark = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
  text_transform(
        locations = cells_body(columns = team_wordmark),
        fn = function(x){web_image(url=x)}
      ) %>%
  cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
    team_wordmark ~ px(115)
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('darkred','white','darkgreen'),
                 domain = c(-10.22,9.33)
  )

bottom_16 <-
team_rankings%>%
  tail(16)%>%
  inner_join(nflfastR::teams_colors_logos, by = c('club' = 'team_abbr'))%>%
  select(club,team_logo_espn,team_wordmark,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header("Bottom Half Team AdjTVOE ") %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_hide(c(club,team_logo_espn)) %>%
  cols_label(
    team_wordmark = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
  text_transform(
        locations = cells_body(columns = team_wordmark),
        fn = function(x){web_image(url=x)}
      ) %>%
  cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
    team_wordmark ~ px(115)
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('darkred','white','darkgreen'),
                 domain = c(-10.22,9.33)
  )

Team_Table <- gtExtras::gt_two_column_layout(list(top_16,bottom_16))

Team_Table
```

```{r}
db_tbl<-db_rank %>%
  inner_join(nflfastR::teams_colors_logos, by = c('club' = 'team_abbr'))%>%
  select(team_logo_espn, displayName, position,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header("Individual Defensive Back Rankings by AdjTVOE") %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_label(
    team_logo_espn = '',
    displayName = '',
    position = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
  text_transform(
        locations = cells_body(columns = team_logo_espn),
        fn = function(x){web_image(url=x)}
      ) %>%
  cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
    team_logo_espn ~ px(50)
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('darkred','white','darkgreen'),
                 domain = c(-2,3.91)
  )

lb_tbl<-linebackers_rank %>%
  inner_join(nflfastR::teams_colors_logos, by = c('club' = 'team_abbr'))%>%
  select(team_logo_espn, displayName, position,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header("Individual Linebacker Rankings by AdjTVOE") %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_label(
    team_logo_espn = '',
    displayName = '',
    position = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
  text_transform(
        locations = cells_body(columns = team_logo_espn),
        fn = function(x){web_image(url=x)}
      ) %>%
  cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
    team_logo_espn ~ px(50)
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('white','darkgreen'),
                 domain = c(2,5.54)
  )
lb_tbl


de_tbl<-defensive_front_rank %>%
  inner_join(nflfastR::teams_colors_logos, by = c('club' = 'team_abbr'))%>%
  select(team_logo_espn, displayName, position,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header("Individual Defensive Line Rankings by AdjTVOE") %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_label(
    team_logo_espn = '',
    displayName = '',
    position = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
  text_transform(
        locations = cells_body(columns = team_logo_espn),
        fn = function(x){web_image(url=x)}
      ) %>%
  cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
    team_logo_espn ~ px(50)
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('darkred','white','darkgreen'),
                 domain = c(0,6)
  )
de_tbl
```

```{r}
browns_tbl <- browns%>%
  select(displayName,position,tackle,pred_Tackle,Adj_TVOE)%>%
  gt()%>%
  tab_header(title = "2022 Cleveland Browns Defense by AdjTVOE",
             subtitle = 'Weeks 1 - 9') %>%
  fmt_number(columns = Adj_TVOE)%>%
  cols_label(
    displayName = 
      html(
        web_image(url=	'https://github.com/nflverse/nflfastR-data/raw/master/wordmarks/CLE.png')
      ),
    position = '',
    tackle = 'Total',
    pred_Tackle = 'Predicted',
    Adj_TVOE = 'AdjTVOE'
  ) %>%
cols_width(
    tackle~px(80),
    pred_Tackle ~ px(80),
    Adj_TVOE ~ px(80),
  ) %>%
  tab_spanner(columns = c(tackle,pred_Tackle),
              label = 'Tackles') %>%
  cols_align(align = 'center') %>%
  data_color(columns = Adj_TVOE, 
                 method = "numeric",
                 palette  = c('darkred','white','darkgreen'),
                 #domain = c(0,6)
  )
```



